name: ci

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:

    runs-on: ubuntu-latest
    steps:
      - name: shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vishnu123vis/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
    
     - uses: actions/checkout@v3

     - name: modify values filesx
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          if ! command -v yq &> /dev/null; then
            curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /tmp/yq
            chmod +x /tmp/yq
            sudo mv /tmp/yq /usr/local/bin/yq 2>/dev/null || mv /tmp/yq /usr/local/bin/yq
          fi
          yq -i ".image.tag = \"${{ needs.ci.outputs.commit_id }}\"" charts/python-app/values.yaml
          yq -i ".image.tag = \"${{ needs.ci.outputs.commit_id }}\"" charts/argocd/values-argo.yaml

      - name: Commit changes
        uses: Endbug/add-and-commmit@v9
        with:
          message: "Update image tag to ${{ needs.ci.outputs.commit_id }}"

      - name: install argocd
        shell: bash
        run: |
          if ! command -v argocd &> /dev/null; then
            curl -Lf -o /tmp/argocd https://github.com/argoproj/argo-cd/releases/download/v2.14.2/argocd-linux-amd64
            chmod +x /tmp/argocd
            sudo mv /tmp/argocd /usr/local/bin/argocd
          fi
      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

